server:
  port: 8083
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10


# 微信公众号对接
weixin:
  config:
    originalid: wxa2ac9e73e0bc3eba
    token: paradoxHub
    app-id: 123
    app-secret: 12
    template_id: 12

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:13306/s-pay-mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat


mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app_id: 9021000141648382
  merchant_private_key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCcAikKT3OMbX3d+QGIUQtvMftxlawb1hVlX0raarXMdEIpvEhrxWpmt1bTsWYdWrNlHAS/J0XccJN+K470Pqf9KMW2y4Q/svK2PdyQARI8ldn9MlwqE+q+iY/nnYwWwA3zNGtqbXiZpG1YNXsFx7ooqbmXCe5g1YCxwtU2PbUIBfgh0ABW6bNhnkmk+x4oW0kz58cG/hpiiyu5J/ICPW/544FCFTe4NQOTnhgEg+oTR0/N3WDu8pRO39aE2ARcfMF/2rn062y5hRgqgmR8CprSlahZTX8352dhahWv2GraqvRIF1nAwQ0yRHA9qmU1mG6lZ/iXVqeFOJeBXyfMfbkZAgMBAAECggEAAzdML0k6AZAUQyop7Ox2xuEJ5OqH9L7yC/ft7Bi9DKzs3D1kZMxaCCoJYS3MBBjlj9UHCAXAO+4aLESrmr9b6S0Y/k6tuD5xIG6gCFvtS1BvgPezzK5CbZEaZVTrGWD2KKhQ+o2tKcWo92OK2LCoVsRA7isnPdnI4GE60fZtr++fUg1O2tjONu4NsE6Q800LhbZz+XgP5mttERkWT44VxijVgX557zeZ1cuYNMXAEWVDiZhpiFIYCuwAIESNrU3cRtfpgQDUtmdQrw4WLfDRGWmeSLH8iSzDQsUIWy+/uHmX4SbCEjrKIMndI2VwOGbCElSOW4a12pAWBCd28BOxbQKBgQDPhcMdWFuYoGDIhsy9p3MNmP9DNn669uS6QtGwjd11T5eLcR6rXzOOQ8Qp4fhc+fCk2CE1uWGVUyFJpjv9hzx4cwtBeSYldnB+r5LtIJ+koUynFqKoK9rBKtxwlhVQo7lXd6m8Ft4O+AY40uQPlcQkpZxfi3ShVYMw5AxDMxhKHwKBgQDAc8JvYGVaSKyeCp2O9B4UzkO38FMm3IYjSxqtuIQb+A/EG6APV8Ruy1EeYpnLCMpE2hRBzx+c0y96Dy3xox/FykOPzoOUVvi6YZZcokmaoDCeSaCQVkXK34Wpm1pVGnX/liJYsR0ZNwXzuFsn/N9hGaLqs2Do9AfojwVf2qaFxwKBgDA0GvFbD9OxFSofHbnEBpaW/lwncWKObOzTDpAbM+DG/yWVvhECiSA3n343DhDSwdIYngYzrHYaHDZWVcL7QdGcr3Wi5Xh4PYM/1zobhNmh2gNJ37h+j06lXRUN15+mmCu4EQYurZ/+frt+SRlRqYD1sxACfbHoAhQ+NJb7bF3zAoGAJqjaXR9DHODOdCzzu5zEUi+hINkRCxRvibVzlYQkXa32FNHr1EkwN4V2NSFffY61eyFHwnSGCC3QMrfL5ed74XKhIck9W1YhPueNmewr1vjo61MlAvmhqYA/THPdsIzROVeCbMifbMpF0tCs1xqQEORier0v8Xvb/taEIN4+Z08CgYAOVrqGkcYvAlqHIwW0N2VScWZGxopeqiq2WE5aQXmDdPHWhT+s6mnB2MlH0aBHZ8j9aDkioLTOrYy6LwQVNGAG/r2Q1qp3NAOYG9VmLJG7Fqr6WcqUg39sCnBvcPm0SvW/ePa83K8/fOUT8xn1DEXogsuBQ3biAaGek9K3/5Vrbw==
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAj0P0l7WAQiGUNAVN6NLt1mDfgZtaDPu7c8ytF1xVC6X8/a28MgaFyGig0DcBZFmOGB+W9iyhDhT18S3nwCP0YsIf0VeSHD/1jh2Ds+QUB4Oc0oazEXvnYwOhCdnPeryuW/PzM4TvzxS+ElClbhSHG75NJGylM8vAvCcpShUu7th3gVN/wK5wp2a8cbh5f3uETkScYY/pxUipAvzpoReW2M+9D1o/HAcP1PN2d0dCK+2dFr6NTjhB3yejYTZSL3SUtUKH5ZjvVPIh7C2uU+u8o+tacRZENiBTtogsTMp7lh1hOkA7A8XjwJ7lc0HwbY/B2TzS8mAsztb7M6yQFjAkLwIDAQAB
  notify_url: http://117.72.38.149:8080/alipay/alipay_notify_url
  return_url: https://baidu.com
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do



# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml




